### ISSUE TITLE
Compatability with Age of Empires II: Definitive Edition

### ISSUE THREAD

**Issue by HumzaCrumza** [IamFlea/bartender#11]
Hi! I'm a new-ish content creator on Youtube for AoE 2 videos and a viewer of mine sent me this piece of work. Unfortunately, I don't think it's compatible with AoE 2 DE. Is there any way to modify this code to get it working there?

**Comment by IamFlea** [comment]
Hello, yes, you are correct, it works only for HD version. I believe there is a simple way how to modify to DE version. However, I don't own it and my computer is slow for that. Anyway, you might be interested in Capture Age, https://captureage.com/ Maybe more projects are running on Siege Engineers Discord https://aoe2.se/
