### ISSUE TITLE
hi! i can use this on steam? how do i install it?

### ISSUE THREAD

**Issue by patoomartinez** [IamFlea/bartender#12]

**Comment by IamFlea** [comment]
**Get dependencies**
Python 3.6  (I haven't tested newer versions) 
PyQt5 (pip3 install PyQt5)
pywin32 (pip3 install pywin32)

And then in command line you can run either `start.bat`  or `python bartender.py` 
So far, yes, you can run it on Steam AoE HD (2013), but I don't recommend using it in multiplayer.
