### ISSUE TITLE
I can make it run like this now, what should I do to further extract the information? help plz

### ISSUE THREAD

**Issue by learner501** [IamFlea/bartender#13]
![run_image](https://github.com/IamFlea/bartender/assets/145905743/984e711d-4213-469c-bc6a-56c7f3d676e8)

**Comment by IamFlea** [comment]
Hello.  I haven't opened this project for long time.  I think I should archive it.  I believe there has been several game updates for AoE2 (2013 version).  You need to get the right memory offset for:

https://github.com/IamFlea/bartender/blob/a9865ade2235e925708e202b94abe0861acc7400/aoc_game.py#L68
https://github.com/IamFlea/bartender/blob/a9865ade2235e925708e202b94abe0861acc7400/aoc_game.py#L103

You need to find these offsets and addresses in the memory.  Also it is possible that other offsets have changed in last five years.
