### ISSUE TITLE
Update cheating FAQ

### ISSUE THREAD

**Issue by coffenbacher** [IamFlea/bartender#8]
```
> This is cheating!

It is not. Bartender does not provide you information about your enemy.
```

This should be updated to say that this is not at all an accepted viewpoint by the community, and is in fact widely considered cheating. Trying to use this on Voobly would result in a ban, for example.

**Comment by blkpanther** [comment]
So let's have an open(minded) discussion about this.
After I started playing AoE (1999) players suggesting to have Quality of Life (QoL) features like Multi Queue (MQ), Unlimited Farm reseeding, more prominent display of enemy Age or bigger selection size would lower the skillcap and was frowned upon.
If someone altered the game to have more visibility than the game provided out of the box, that person was considered a hacker and should be banned from ever playing against other people again.

Yet here we are with AoC (The Conquerors - official Expansion) QoL improvements, voobly MQ and new supported hotkeys.
Yet here we are with a display of the age beside enemy player names.
Yet here we are with small trees, grid mod, no snow, short walls and a hundred other visibility changes to the game.
Yet here we are with palisade/farm scouting. On voobly. Done by every pro and expert player in existance.

I'm not sure voobly would ban you for it (considering it cheating and detecting it are 2 different things) ... but I also know that you will be banned for having a screenshot tool, file manager or other stuff running that never even interacts with voobly/AoE2. Sometimes even minimizing it will get you banned.
On the other hand don't forget the history ... with Elysium/Tormentium selling hacks, distributing his own patches for those hacks only to sell newer hacks.
That were dark times and no fun to play. Please don't compare bartender that only displays known things more prominent/permanent to hacks, that show unknown things, change things or automate clicks etc.

I have to admit, I got used to spectator overlay on voobly. So why not have your own villager/fishing ship/trade cart count and current researches displayed while playing.

And if Microsoft is unable to get AoE into the new millenium - like they have proven time and time again - the community has to step in. Like we (the players) always did and always will. See userpatch, voobly, mods, guides, support and so much more.

There are lots of things bartender could implement that I would consider cheating. Where do you draw the line?

**Comment by coffenbacher** [comment]
Sry, don't have time to respond in detail at the moment, but open-minded discussion and explicit acknowledgement of the concerns = 👍 from me. A simple "It is not." = 👎from me.

**Comment by IamFlea** [comment]
Please, read carefully. Bartender doesn't work for Voobly version of AoE. 

I'd like to see coding issues here and not flame wars, thus I locked this thread. For the further discussion, please use different way of communication on [reddit](https://www.reddit.com/r/aoe2/comments/91i9eb/bartneder_overlay_for_aoe2hd_is_open_source_see/).
