### ISSUE TITLE
Technologies not updating if game loaded/restored

### ISSUE THREAD

**Issue by IAmJulianAcosta** [IamFlea/bartender#9]
Currently if you have to restore a game, the technologies stored in `player.research.done` are clear, as that array is dynamically populated during the game. 

I know the information is somewhere in memory as after loading a saved game:

![image](https://user-images.githubusercontent.com/1844640/52537425-bd5c4180-2d34-11e9-88d2-78db9c12d1a0.png)

Maybe finding the pointer where the researched technologies are stored would be a way to fix it?

**Comment by IamFlea** [comment]
Thanks for the report. It should be fixed now.

I would like to invite you to Siege Engineers group on Discord. https://discord.gg/jbXYV2 
We are a group of programmers who love AoC and code some mods. Also you can visit our github page on: https://github.com/SiegeEngineers

**Comment by IAmJulianAcosta** [comment]
Hey thank you, that was really fast, I joined the server, are you with the same username?
